name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
          cross: true
        - target: aarch64-unknown-linux-musl
          os: ubuntu-latest
          cross: true
        - target: x86_64-apple-darwin
          os: macos-latest
          cross: false
        - target: aarch64-apple-darwin
          os: macos-latest
          cross: false
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          cross: false

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}

    - name: Run Cross
      if: ${{ matrix.cross }}
      run: |
        cargo install cross --git https://github.com/cross-rs/cross.git
        cross build --release --target ${{ matrix.target }}

    - name: Run Cargo
      if: ${{ !matrix.cross }}
      run: cargo build --release --target ${{ matrix.target }}

    - name: create artifact directory
      shell: bash
      run: |
        directory=${{ github.repository }}-${{ matrix.target }}
        mkdir $directory
        cp README.md LICENSE $directory
        if [ -f target/${{ matrix.target }}/release/${{ github.repository }}.exe ]; then
          cp target/${{ matrix.target }}/release/${{ github.repository }}.exe $directory
          7z a -r $directory.zip $directory
        else
          cp target/${{ matrix.target }}/release/${{ github.repository }} $directory
          tar cJf $directory.tar.xz $directory
        fi

    - uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "${{ github.repository }}-${{ matrix.target }}.*"
        allowUpdates: true
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true